Refactoring

diff --git a/debpack b/debpack
--- a/debpack
+++ b/debpack
@@ -1,20 +1,6 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-patch_control() {
-    # Parse field
-    key=$(echo "$2" | cut -d: -f1)
-    value=$(echo "$2" | cut -d: -f2- | sed "s/^[[:space:]]*//")
-
-    # Remove any pre-existing fields with same name
-    # Ignore non-zero exit if $1 is empty
-    grep -Fiv "${key}:" "$1" > "$1.tmp" || true
-
-    # Add new field
-    echo "${key}: ${value}" >> "$1.tmp"
-    mv "$1.tmp" "$1"
-}
-
 # Only output color if stdout is a TTY
 color_echo() {
     if [[ -t 1 ]]; then
@@ -40,6 +26,20 @@ cleanup() {
     if [[ -d .debpack ]]; then
         rm -r .debpack
     fi
+}
+
+patch_control() {
+    # Parse field
+    key=$(echo "$2" | cut -d: -f1)
+    value=$(echo "$2" | cut -d: -f2- | sed "s/^[[:space:]]*//")
+
+    # Remove any pre-existing fields with same name
+    # Ignore non-zero exit if $1 is empty
+    grep -Fiv "${key}:" "$1" > "$1.tmp" || true
+
+    # Add new field
+    echo "${key}: ${value}" >> "$1.tmp"
+    mv "$1.tmp" "$1"
 }
 
 build() {
@@ -101,7 +101,7 @@ build() {
 
 print_usage() {
     cat << EOF
-Usage: $0 [-h] [options] [fields...]
+Usage: debpack [-h] [options] [fields...]
 
 Super simple Debian packages.
 
